# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- release/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  packageVersion: '$(SourceBranchName).$(BuildID)'

name: '[$(BuildID)]$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)'

steps:

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'restore'
    arguments: '--configuration $(buildConfiguration)'
    projects: 'QueryMaster/QueryMaster.csproj'

- script: echo